### ISSUE TITLE
Dark mode!

### ISSUE THREAD

**Issue by baronpumpky** [jakelauer/allbadcards#67] opened 2020-04-19 02:12 UTC
Can we get a dark mode?

**Comment by Dorson** [comment] 2020-04-21 00:46
Made exactly that for the night and evening time.

See live demo on GitHub page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Have fun, feel free to copy, adopt, port, etc...

**Comment by jakelauer** [comment] 2020-04-28 08:11
Dupe of #11

**Closed by jakelauer** 2020-04-28 08:11 UTC
Labels: enhancement
