### ISSUE TITLE
Blank Cards

### ISSUE THREAD

**Issue by bulldogs3401** [jakelauer/allbadcards#179] opened 2020-05-03 04:49 UTC
My idea is...
just empty cards that you can fill in to make things more interesting

**Comment by dennmuel** [comment] 2020-05-03 09:27
Would this be the same as #102, #119 and #120?

**Comment by bulldogs3401** [comment] 2020-05-03 09:29
Yep, sorry about that. I was just putting it out there, thought it might
have been suggested, but never looked into it.

**Comment by dennmuel** [comment] 2020-05-03 10:40
All good, still a cool idea! :) I don't have anything to say in this project, I'm just trying to help by finding duplicates, fixing typos and that kinda stuff.

**Comment by jakelauer** [comment] 2020-05-04 15:50
Yes, dupe of #102 :) Thanks @dennmuel !

**Closed by jakelauer** 2020-05-04 15:50 UTC
Labels: enhancement
