### ISSUE TITLE
Random player hangs

### ISSUE THREAD

**Issue by tomczak724** [jakelauer/allbadcards#125] opened 2020-04-27 01:40 UTC
BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://allbad.cards/game/perfect-robin-50

2. Describe the problem you experienced
One of our random players was hanging when submitting answers, like it was stuck in an infinite loop

3. Did you see any errors?
Nope, it was just hanging

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser = Google Chrome
- Device type = Macbook pro

**Comment by jakelauer** [comment] 2020-04-27 03:27
Yeah, this is a legit problem. Definitely related to my new multiserver setup. For my own context later, this happens because the timer that forces the random player to play is stored in memory, so anytime servers change or a players lose a connection to a server and hit a new server, the timer may no longer expire correctly. It's a very small case - should work correctly 99% of the time.

**Comment by jakelauer** [comment] 2020-04-27 03:29
Also, dupe of #88

**Closed by jakelauer** 2020-04-27 03:29 UTC
