### ISSUE TITLE
Game Settings menus will time out.

### ISSUE THREAD

**Issue by fisherKat289** [jakelauer/allbadcards#276] opened 2020-05-18 21:59 UTC
URL: [https://allbad.cards/game/blue-collar-alligator-293](url)

As I edit the decks or am adding a list of decks in, the UI just closes. It seems like it times out.

I didn't see any actual errors.

This is on Chrome on Mac.

**Comment by jakelauer** [comment] 2020-05-27 07:39
I haven't experienced this or seen other reports. Have you seen this happen since posting?

**Comment by dennmuel** [comment] 2020-05-27 07:54
I can confirm the behaviour for the time this issue was opened. I've tried it again now, but instead of the UI closing immediately I see the lost connection message:
![grafik](https://user-images.githubusercontent.com/21078769/82992551-9a27d500-9fff-11ea-816d-8a7359fc4d21.png)
On clicking retry, the settings menu I opened had closed. I can only assume both phenomena have the same cause, because the timing seems the same.

**Comment by dennmuel** [comment] 2020-05-30 07:43
Update: Happened again yesterday just AS OP describes (no error, just the menu disappearing).
https://allbad.cards/game/specific-prairie-dog-3175

**Comment by jakelauer** [comment] 2020-06-07 22:53
I had a theory about why this was happening, and I fixed the potential issue that I think caused it. Closing for now, but if you see it again, please comment.

**Closed by jakelauer** 2020-06-07 22:53 UTC
