### ISSUE TITLE
Game freezing with error

### ISSUE THREAD

**Issue by hcaz282** [jakelauer/allbadcards#387] opened 2020-07-06 03:10 UTC
Hello,

3 times tonight we had to generate a new link. the first time (2nd person) was setting up the game and the site froze, even though he was logged in it wouldn't let him back in the game. ( created new link)

then twice during the game the card queen got an error message when trying to pick a card. this then forced them to pick the card on the screen, but when the round was over the game would not advance to the next round automatically, and when the button was pushed they got an error message.

I'm sorry, I wasn't able to copy the message.

using allbad.cards
1st person: PC: windows 10, using newist version of firefox
2nd person: PC , windows 10 using google chrome.

Thanks!

***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?

2. Describe the problem you experienced

3. Did you see any errors?

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser
- Device type

**Comment by jakelauer** [comment] 2020-07-17 06:31
dupe of #386

**Closed by jakelauer** 2020-07-17 06:31 UTC
