### ISSUE TITLE
Ability to force start judging (skip a few people)

### ISSUE THREAD

**Issue by 20zinnm** [jakelauer/allbadcards#72] opened 2020-04-19 05:03 UTC
When someone has to step away from the game, it'd be nice to be able to force them to randomly pick by "force starting judging."

**Comment by jakelauer** [comment] 2020-04-19 08:26
Would a round timer suffice for the same problem?

**Comment by 20zinnm** [comment] 2020-04-19 15:56
@jakelauer It probably would. Didn't think of that at 1AM 🤣

**Comment by jakelauer** [comment] 2020-04-27 03:40
Given that, I'll call this a dupe of #89

**Closed by jakelauer** 2020-04-27 03:40 UTC
Labels: enhancement
