### ISSUE TITLE
Idle timer

### ISSUE THREAD

**Issue by augdawg69** [jakelauer/allbadcards#106] opened 2020-04-25 02:55 UTC
Just an idea a 120 or 180 second idol timer that will skip the round if the card czar has left the game.

**Comment by augdawg69** [comment] 2020-04-25 02:55
Just an idea a 120 or 180 second idol timer that will skip the round if the card czar has left the game.

**Comment by jakelauer** [comment] 2020-04-27 03:38
Dupe of #89

**Closed by jakelauer** 2020-04-27 03:38 UTC
Labels: enhancement
