### ISSUE TITLE
Please enable us to be able add custom csv files

### ISSUE THREAD

**Issue by mavrck307** [jakelauer/allbadcards#100] opened 2020-04-24 17:29 UTC
My idea is... please it would be great if you could add a custom card support. We have a deck that was using the playingcards.io remote insensitivity game. so the cards are formatted to a csv file with two sheets prompts and responses.

**Comment by jakelauer** [comment] 2020-04-24 17:46
Dupe of #97

**Closed by jakelauer** 2020-04-24 17:46 UTC
Labels: enhancement
