### ISSUE TITLE
Private Personal packs

### ISSUE THREAD

**Issue by hcaz282** [jakelauer/allbadcards#52] opened 2020-04-18 15:18 UTC
My idea is...
It would be great if you had login capabilities and the ability to make card packs of your own. My friends and I have our own custom packs that are full of inside jokes which are funny to us, but nobody else would understand. We all live in different states. This pandemic has gotten us to play online more, it would be great if we could continue using our packs that we all miss.

Thanks!!
Zach

**Comment by jakelauer** [comment] 2020-04-18 22:53
I'll call this a dupe of #57 because CardCast support will fix this

**Closed by jakelauer** 2020-04-18 22:53 UTC
Labels: enhancement
