### ISSUE TITLE
Translation features

### ISSUE THREAD

**Issue by thassae** [jakelauer/allbadcards#218] opened 2020-05-09 15:48 UTC
I do think you could engage the community to translate this to other languages. I could contribute with Portuguese.

**Comment by bastiannunezb** [comment] 2020-05-10 03:10
A good platform for this is Transifex. I could contribute with Spanish.

**Comment by jakelauer** [comment] 2020-05-11 17:04
Dupe of #112 - This is a bit complex. Transifex is expensive!

**Closed by jakelauer** 2020-05-11 17:04 UTC
Labels: enhancement
