### ISSUE TITLE
Voting instead of Czars

### ISSUE THREAD

**Issue by DeathwatchDoc** [jakelauer/allbadcards#94] opened 2020-04-23 12:53 UTC
My idea is...
Add an option to have the winning card(s) selected by a voting system among human players. This is one of our favorite house rule variants and lets everyone play every round preventing the dreaded "Why do I always have the best cards on the rounds I have to judge?" suffering.

**Comment by CryoRig** [comment] 2020-04-30 09:54
Would love that as an option, but please make it so that you can not vote for your own Card
Or everybody is just gonna vote for themself...

**Comment by DeathwatchDoc** [comment] 2020-05-01 21:43
We always play it with that specified, forgot to put it in the request as it is second nature. Good catch, thanks!

**Comment by jakelauer** [comment] 2020-05-05 06:58
Dupe of #71

**Closed by jakelauer** 2020-05-05 06:58 UTC
Labels: enhancement
