### ISSUE TITLE
Computer Player

### ISSUE THREAD

**Issue by Tolure** [jakelauer/allbadcards#15] opened 2020-04-16 00:36 UTC
In our home games we usually grab the top card of the deck as the random / computer player. 

It would add joy when this card would win and sometimes that player would actually have more points than anyone else. 

Either have a player that plays a random card or a basic AI (Tensorflow) that tries to choose the best card based on the cards players choose as the winning one.

**Comment by jakelauer** [comment] 2020-04-16 00:58
Dupe of #10

**Closed by jakelauer** 2020-04-16 00:58 UTC
Labels: enhancement
