### ISSUE TITLE
Option for occasional write-in cards

### ISSUE THREAD

**Issue by rbezar** [jakelauer/allbadcards#375] opened 2020-07-01 04:15 UTC
I played the game last night with write-ins, but I encountered a problem when all my friends just wrote their answer on the blank card for every round, which basically just defeated the point of the game. I'd like to suggest an option where write-in cards will only be available once every _ rounds (this number could be 5, or adjustable by an optional slider). This would introduce write-ins without breaking the game.

**Comment by jakelauer** [comment] 2020-07-31 08:12
Dupe of #331

**Closed by jakelauer** 2020-07-31 08:12 UTC
Labels: enhancement
