### ISSUE TITLE
https://allbad.cards/game/smooth-treefrog-53

### ISSUE THREAD

**Issue by ronansimpson5** [jakelauer/allbadcards#50] opened 2020-04-18 14:48 UTC
1. What URL was your game at?
https://allbad.cards/game/smooth-treefrog-53
2. Describe the problem you experienced
after completing one game, we played another and were unable to choose the "my cards suck option" - this was the same for all players
3. Did you see any errors?
just the inability to select the "my cards suck" option at any point during the game
4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Google Chrome
- Macbook Pro 2019

**Comment by jakelauer** [comment] 2020-04-18 22:54
Dupe of #16

**Closed by jakelauer** 2020-04-18 22:54 UTC
