### ISSUE TITLE
Show winning combinations

### ISSUE THREAD

**Issue by bkirst** [jakelauer/allbadcards#346] opened 2020-06-07 19:17 UTC
We like to go over all the winning combinations at the end of the game to get one last chuckle. It'd be nice to have an option to be able to see all winning hands during or at the end of the game.

**Comment by jakelauer** [comment] 2020-06-07 22:50
Dupe of #78

**Closed by jakelauer** 2020-06-07 22:50 UTC
Labels: enhancement

**Comment by bkirst** [comment] 2020-06-08 00:50
Would it be any easier to have a feature to post the text of the cards to chat at the end of a round? We're doing this manually right now.
