### ISSUE TITLE
When importing JSON 

### ISSUE THREAD

**Issue by tracylclark** [jakelauer/allbadcards#364] opened 2020-06-15 05:19 UTC
URL: https://allbad.cards/pack/detail

ISSUE : When selecting import from JSON I get this error message: "TypeError: "Invalid attempt to spread non-iterable instance" in the console (add to pack and replace pack has the same behavior), the name of the pack clears itself and displays the error message "Cannot Save Pack name must be at least 3 characters long" (in the DOM), and after filling in the pack name again, displays the error "Cannot Save You need at least one card" (in the DOM).

BROWSER: 
Firefox Version 77.0.1 64-bit
Chrome Version 83.0.4103.97 (Official Build) (64-bit) - replicated the issue

DEVICE: PC 

ADDITIONAL DETAILS: JSON file matches the published Schema per an independent JSON Schema checker. JSON includes 429 black cards, 1381 white cards, 1810 total cards.

**Comment by jakelauer** [comment] 2020-06-15 05:30
Can you email the pack in question to allbadcards@gmail.com?

**Comment by jakelauer** [comment] 2020-06-15 05:30
Also, you might want to try just refreshing the pack creation page. I made a modification to it today.

**Comment by dennmuel** [comment] 2020-06-15 10:36
I can confirm this behavior; refreshing does not help. You can find my packs for testing [here](https://github.com/dennmuel/custom-packs/tree/master/packs).

**Comment by jakelauer** [comment] 2020-06-15 15:58
Ahh, I see - if you are using the exported format from the CardCast export, that format has now changed. Your report did reveal a bug, which is that I did not update the schema that the validation uses, so the message it gave you was not helpful. I've updated that now, but your imports will still fail because they match the old version.

Here are your options:

1) Re-export from CardCast using https://allbad.cards/cardcast-export
2) Export your existing pack on All Bad Cards to get it into the correct format for editing
or, if you have already made edits to a JSON file and need to get them into All Bad Cards,
3) Modify your schema to match the following schema:

```

	"type": "object",
	"properties": {
		"packName": {"type": "string"},
		"blackCards": {
			"type": "array",
			"items": {"type": "string"}
		},
		"whiteCards": {
			"type": "array",
			"items": {"type": "string"}
		}
	},
	"required": ["packName", "blackCards", "whiteCards"]
```

**Comment by dennmuel** [comment] 2020-06-15 17:02
Thanks for the quick help, @jakelauer!
I wonder about one thing in the new schema, though: How does ABC determine the number of white cards required to answer if it is not provided in the schema for black cards?

**Comment by jakelauer** [comment] 2020-06-15 17:11
The `pick` number is (and always has been) determined by the number of `_` occurrences in the black card string. Even when you could specify the `pick` number in JSON, it was ignored when saving the pack. In other words, the only way to require an answer in a black card is to put in a `_` character.

**Comment by jakelauer** [comment] 2020-06-15 17:12
I'll close this out, but if there are more issues, we can re-open it.

**Closed by jakelauer** 2020-06-15 17:12 UTC

**Comment by tracylclark** [comment] 2020-06-15 21:39
After updating the JSON schema I was able to get it working, thanks for the update.
