### ISSUE TITLE
Record of cards played

### ISSUE THREAD

**Issue by chrisba11** [jakelauer/allbadcards#107] opened 2020-04-25 04:09 UTC
I found myself wanting to take screenshots of the cards that were played, but if another user hit the next round button too early, I couldn’t get it in time. If there was a way to share the current round as an image or have a full history of the rounds played, that would be awesome.

**Comment by jakelauer** [comment] 2020-04-30 19:54
Dupe of #78

**Closed by jakelauer** 2020-04-30 19:54 UTC
Labels: enhancement
