### ISSUE TITLE
In an all-AI game, possible to remove all players from game and leave it in a state which can't be escaped.

### ISSUE THREAD

**Issue by gregx1337** [jakelauer/allbadcards#385] opened 2020-07-05 07:56 UTC
***NOTE***: IF YOU DO NOT PROVIDE DETAILS, YOUR BUG WILL BE CLOSED

BEFORE SUBMITTING:
Please fill out the following to the best of your ability, to help with investigating your report.

1. What URL was your game at?
https://talkingouturanus.com/game/renewable-goose-1349/
Duplicated bug at:
https://notallbad.cards/game/white-mule-2728/

2. Describe the problem you experienced
Created a game with 2 other AI players (only) and played a few rounds. Removed both AI players during my Card Captain round and was left with a card choice screen with no cards and no working controls. I was unable to choose "Leave Game" for myself from the Scoreboard also. Attempting to revisit the URL (even after truncating it to remove /play/) returned me to the exact same state.

3. Did you see any errors?
No errors.

4. Screenshots - If applicable, add screenshots to help explain your problem.

5. Additional information
Please provide any additional helpful information, like:
- Browser: Chrome 83.0.4103.116
- Device type: Windows 10 Desktop

**Comment by jakelauer** [comment] 2020-07-17 06:31
essentially a dupe of #289

**Closed by jakelauer** 2020-07-17 06:31 UTC
